# Generated by Django 4.0 on 2023-08-17 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('gln_branch', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('gln_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('gtin_producto', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeField', models.DateTimeField(auto_now=True)),
                ('final_count', models.IntegerField(default=0)),
                ('price_unity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gln_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.branch')),
                ('gln_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.client')),
                ('gtin_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.product')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
